SET(moocpp_sources
    moocpp/moocpp.cmake
    moocpp/fileutils.h
    moocpp/fileutils.cpp
    moocpp/gobjptr.h
    moocpp/gstr.h
    moocpp/gstr.cpp
    moocpp/moocpp.h
    moocpp/util.h
)
